#!/bin/bash

location=$1
fcount="0"
dcount="0"

if [ $# -gt 0 ]
then
    if [ $location = "-h" ]
    then
        echo "Usage: ./labq1.sh [ file [ file ... ] ]"
        exit 1
fi

filecount(){
for file in $location/*
do
    if [ -f "$file" ]
    then
            ((fcount++))
        elif [ -d "$file" ]
        then
            ((dcount++))
            filecount $file
fi
done
}

while [ "$location" ]
do
    filecount $location
    shift
done

echo "files: $fcount"
echo "directories: $dcount"
